version: 2

default_config: &default_config
  docker:
    - image: ubuntu:bionic
  working_directory: ~/circleci/coffeelove
  environment:
    ANDROID_HOME: "/usr/lib/android-sdk"

jobs:
  build:
    <<: *default_config
    steps:
      - checkout
      - add_ssh_keys
      - run:
          name: Fetch CocoaPods repository
          command: |
            apt update -y && apt install -y curl wget git
            curl https://cocoapods-specs.circleci.com/fetch-cocoapods-repo-from-s3.sh | bash -s cf
            # Fetch cocoapods specs from S3 instead of github
      - run:
          name: Setup system dependencies
          command: |
            apt update -y && apt install -y android-sdk
            cd $ANDROID_HOME
            wget https://dl.google.com/android/repository/commandlinetools-linux-6200805_latest.zip
            unzip -o commandlinetools-linux-6200805_latest.zip
            echo y | $ANDROID_HOME/tools/bin/sdkmanager  --sdk_root=${ANDROID_HOME} "platform-tools" "platforms;android-25" "build-tools;25.0.2" "extras;android;m2repository" "extras;google;m2repository"
            apt -y install curl dirmngr apt-transport-https lsb-release ca-certificates
            curl -sL https://deb.nodesource.com/setup_12.x | bash -
            apt -y install nodejs gcc g++ make
            cd ~/circleci/coffeelove
      - restore_cache:
          key: npm-cache-{{ checksum "./package-lock.json" }}
      - run:
          name: "Install node dependencies"
          command: |
            npm install
            npm install -g nativescript
            npx tns usage-reporting disable
            npx tns error-reporting disable
      - save_cache:
          key: npm-cache-{{ checksum "./package-lock.json" }}
          paths:
            - ~/.npm
      - run:
          name: "Rebuild Node SASS bindings"
          command: npm rebuild node-sass --force
      - run:
          name: "Prepare Android"
          command: npx tns prepare android
      - run:
          name: "Build Android"
          command: |
            ./scripts/build_android.sh
      - persist_to_workspace:
          root: ~/circleci
          paths:
            - coffeelove

  deploy:
    <<: *default_config
    steps:
      - attach_workspace:
          at: ~/circleci
      - run:
          name: "Deploy"
          command: |
            npx tns usage-reporting disable
            npx tns error-reporting disable
            ./scripts/deploy.sh

workflows:
  version: 2
  build-test-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
